version: '3.8'

services:
  # The Database Warehouse Storage Room
  db:
    image: postgres:15
    container_name: autosql_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Layer 1 & 2: The High-Performance Go Network Proxy Cop
  autosql-proxy:
    build: ./proxy-engine
    container_name: autosql_proxy_service
    ports:
      - "5433:5433"
    depends_on:
      - db

  # Layer 3: The API Token Protected Python AI Brain
  ai-optimizer:
    build: ./ai-engine
    container_name: ai_optimizer_service
    ports:
      - "8000:8000"

volumes:
  pgdata: